### ISSUE TITLE
Error 401 when uploading the source-map only with some files / uploads

### ISSUE THREAD

**Issue by blopa** [bugsnag/webpack-bugsnag-plugins#47]
### Describe the bug
I was deploying the implementation of the source-map upload in our production build, when the deploy failed with this error:

```
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/cms/0-7e84539c28831fe607e7.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/cms/1-cf1acf6cafb554718f1d.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/cms/2-2b08f22fa36c994f75fa.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/cms/3-f101a22be949833a71f4.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/cms/4-2c0e6934e04006e67e0d.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/cms/5-90c00338f30394396427.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/cms/6-10660080fbcec74bda7d.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/cms/7-c438222d7cf45f490e12.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/cms/8-b6751746a819b4b756d7.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/cms/9-2ae8db8564fd8c9adb6d.js"
Error: HTTP status 401 received from upload API
    at /data/www/my_site/node_modules/bugsnag-sourcemaps/lib/request.js:41:21
    at ConcatStream.<anonymous> (/data/www/my_site/node_modules/bugsnag-sourcemaps/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:326:22)
    at ConcatStream.EventEmitter.emit (domain.js:548:15)
    at finishMaybe (/data/www/my_site/node_modules/bugsnag-sourcemaps/node_modules/readable-stream/lib/_stream_writable.js:624:14)
    at afterWrite (/data/www/my_site/node_modules/bugsnag-sourcemaps/node_modules/readable-stream/lib/_stream_writable.js:470:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  isRetryable: false
}


[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/node/node/0-bf973c8ec98d2c354e69.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/node/node/1-39bc5313ecd7d834e706.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/node/node/2-42ab8d74bf777cad2948.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/node/node/3-5fa84e8b0dd0bec05df5.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/node/node/4-4e41d7bb0b4a44d6e3ef.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/node/node/5-2cb9a658a641fde517e5.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/node/node/6-8dff268489e82c386243.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/node/node/7-83ca9c1eb0b701a2202f.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/node/node/8-1327d65833d914b96d16.js"
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://mysite.com/build/node/node/9-ce094376488d6e41f6d0.js"
```

From what I read in the documentation, the error 401 means invalid apiKey, but if that's the case, why did it failed only with one specific file and not all of them? 

### Steps to reproduce
1. Not sure

### Environment
* Node version: 14.14.0
* yarn version: 1.22.10
* Webpack version: 4.44.2

### Example code snippet

```
module.exports = [
   ...stuff,
       plugins: [
        isProduction && new BugsnagSourceMapUploaderPlugin({
            apiKey: process.env.OUR_KEY,
            releaseStage: process.env.OUR_STAGE,
            overwrite: true,
        }),
    ],
]
```

**Comment by blopa** [comment]
Well, apparently the API was indeed wrong, even though it uploaded a couple of files.
